### ISSUE TITLE
issue #1 dao-final: scripts/1-initialize-sdk.js

### ISSUE THREAD

**Issue by Artedys** [buildspace/buildspace-dao-final#16]
the final version give this bug (the legacy was OK)

const sdk = ThirdwebSDK.fromPrivateKey(
                        ^

TypeError: ThirdwebSDK.fromPrivateKey is not a function
    at file:///home/runner/

I am in Replit node -v
v16.7.0

Mac OSX 

for information package.json:

{
  "name": "my-dao",
  "version": "3.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@thirdweb-dev/react": "^3.5.1",
    "@thirdweb-dev/sdk": "^3.5.1",
    "ethers": "^5.6.6",
    "react": "^18.0.2",
    "react-dom": "^18.0.2",
    "@vitejs/plugin-react": "^2.0.0",
    "vite": "^3.1.4"
  }
}

**Comment by nachoiacovino** [comment]
make sure you put a semicolon before the `(async`

**Comment by Artedys** [comment]
Hi Nacho,

Thank you for this message.

Here is the script (with the semicolon of course) and the result is attached

import { ThirdwebSDK } from "@thirdweb-dev/sdk";

// Importing and configuring our .env file that we use to securely store our environment variables
import dotenv from "dotenv";
dotenv.config();

// Some quick checks to make sure our .env is working.
if (!process.env.PRIVATE_KEY || process.env.PRIVATE_KEY === "") {
  console.log("🛑 Private key not found.");
}

if (!process.env.QUICKNODE_API_URL || process.env.QUICKNODE_API_URL === "") {
  console.log("🛑 QuickNode API URL not found.");
}

if (!process.env.WALLET_ADDRESS || process.env.WALLET_ADDRESS === "") {
  console.log("🛑 Wallet Address not found.");
}

const sdk = ThirdwebSDK.fromPrivateKey(
  // Your wallet private key. ALWAYS KEEP THIS PRIVATE, DO NOT SHARE IT WITH ANYONE, add it to your .env file and do not commit that file to github!
  process.env.PRIVATE_KEY,
  // RPC URL, we'll use our QuickNode API URL from our .env file.
  "goerli"
);

(async () => {
  try {
    const address = await sdk.getSigner().getAddress();
    console.log("👋 SDK initialized by address:", address)
  } catch (err) {
    console.error("Failed to get apps from the sdk", err);
    process.exit(1);
  }
})();

// We are exporting the initialized thirdweb SDK so that we can use it in our other scripts
export default;
<img width="602" alt="Capture d’écran 2022-11-10 à 18 30 48" src="https://user-images.githubusercontent.com/8425280/201165859-d29ff02d-6e52-4ec5-8e8c-f4f627b50bbe.png">

**Comment by Artedys** [comment]
I close because it works OK in TERMINAL / but with a issue in REPLIT
<img width="609" alt="Capture d’écran 2022-11-12 à 12 59 46" src="https://user-images.githubusercontent.com/8425280/201472923-742365fa-88ef-415b-bdf1-7b3f70790edd.png">
