### ISSUE TITLE
issue  #2 

### ISSUE THREAD

**Issue by Artedys** [buildspace/buildspace-dao-final#17]
npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers

create ERROR

<img width="626" alt="Capture d’écran 2022-11-10 à 08 56 13" src="https://user-images.githubusercontent.com/8425280/201158629-0ad17c08-8c6b-42e7-a05d-15af1006df60.png">

my configuration: Mac OSX
node 16.7
Replit

**Comment by nachoiacovino** [comment]
what version of react are you in? should be 18.2.0

**Comment by Artedys** [comment]
package.json

{
  "name": "my-dao",
  "version": "3.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@thirdweb-dev/react": "^3.5.1",
    "@thirdweb-dev/sdk": "^3.5.1",
    "ethers": "^5.6.6",
    "react": "^18.0.2",
    "react-dom": "^18.0.2",
    "@vitejs/plugin-react": "^2.0.0",
    "vite": "^3.1.4"
  }
}

**Comment by Artedys** [comment]
the node_modules in Replit are the problem but I upgraded 
when I run: npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers I am supposed to run the latest react version.
<img width="594" alt="Capture d’écran 2022-11-10 à 19 06 01" src="https://user-images.githubusercontent.com/8425280/201172865-48932aae-c19f-42b4-99ee-4f162c579d36.png">

**Comment by nachoiacovino** [comment]
yes, you need to be in react 18.2.0

**Comment by Artedys** [comment]
Thank youNacho / but what command to use ?

I use 1/ npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers

and 

2/ npm install react@latest react-dom@latest

both give errors
<img width="600" alt="Capture d’écran 2022-11-10 à 19 15 21" src="https://user-images.githubusercontent.com/8425280/201174841-1c774dcd-2f9e-4408-824f-ac39a65c7757.png">

**Comment by Artedys** [comment]
how to update react in Replit ? How is in your computer ?

**Comment by Artedys** [comment]
Hi Nacho, is me again / this issue has not be solved / we are concerned: https://github.com/thirdweb-dev/react/issues/76

This is unknown error white adding this packages:
npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers
in react.js - react-18 .. my node version is node 18.2.0 ... when i installed these packages react js giving me error. The webpack is not compiled by node. The Stream in webpack node_modules is not defined. bla bla bla..

Plz tell me what's happing going on. ???
watting!

**Comment by Artedys** [comment]
This is unknown error white adding this packages:
npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers
in react.js - react-18 .. my node version is node 18.2.0 ... when i installed these packages react js giving me error. The webpack is not compiled by node. The Stream in webpack node_modules is not defined. bla bla bla..

Plz tell me what's happing going on. ???
watting!

**Comment by Artedys** [comment]
Is the dao-final in a docker with a React version different than 18.2.0 / in this case I can not break the version of React in the docker ? **### **_@third-dev/react@2.3.0 is in Thirdweb_**** <-> you ask me to upgrade Thirdweb ? the only tool I have are npm 

I use 1/ npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers

and

2/ npm install react@latest react-dom@latest

both give errors in ****### _third-dev/react@2.3.0_****

**Comment by Artedys** [comment]
Nacho, please: who are the devs in Thirdweb on this ? **### _@third-dev/react@2.3.0 is in Thirdweb_** (not in my Replit)

**Comment by nachoiacovino** [comment]
I wrote the code for this, you're using an old replit, this the latest updated one: https://replit.com/@thirdweb/buildspace-dao-starter-v3

**Comment by Artedys** [comment]
Thank you Nacho, is the same Replit I run npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers

and I get as above
![Uploading Capture d’écran 2022-11-10 à 20.55.02.png…]()

When you run in your Replit you get different results ? from that ? npm install @thirdweb-dev/react @thirdweb-dev/sdk ethers

I have ~/buildspace-dao-starter-v3-1 V3 / same errors

**Comment by nachoiacovino** [comment]
you shouldn't need to run anything on that replit, it's already using the latest version

**Comment by Artedys** [comment]
I agree with you Nacho, but is the issue #1 if I run dao-final node scripts/1-initialize-sdk.js I get errors liste in issue #1 
<img width="625" alt="Capture d’écran 2022-11-10 à 21 06 48" src="https://user-images.githubusercontent.com/8425280/201195403-782b8073-c019-4431-801e-cce13d8f2447.png">

**Comment by nachoiacovino** [comment]
can you share the code? make sure you add a semicolon after the function
definition (or before `(async`

**Comment by Artedys** [comment]
import { ThirdwebSDK } from "@thirdweb-dev/sdk";

// Importing and configuring our .env file that we use to securely store our environment variables
import dotenv from "dotenv";
dotenv.config();

// Some quick checks to make sure our .env is working.
if (!process.env.PRIVATE_KEY || process.env.PRIVATE_KEY === "") {
  console.log("🛑 Private key not found.");
}

if (!process.env.QUICKNODE_API_URL || process.env.QUICKNODE_API_URL === "") {
  console.log("🛑 QuickNode API URL not found.");
}

if (!process.env.WALLET_ADDRESS || process.env.WALLET_ADDRESS === "") {
  console.log("🛑 Wallet Address not found.");
}

const sdk = ThirdwebSDK.fromPrivateKey(
  // Your wallet private key. ALWAYS KEEP THIS PRIVATE, DO NOT SHARE IT WITH ANYONE, add it to your .env file and do not commit that file to github!
  process.env.PRIVATE_KEY,
  // RPC URL, we'll use our QuickNode API URL from our .env file.
  "goerli"
);

(async () => {
  try {
    const address = await sdk.getSigner().getAddress();
    console.log("👋 SDK initialized by address:", address)
  } catch (err) {
    console.error("Failed to get apps from the sdk", err);
    process.exit(1);
  }
})();

// We are exporting the initialized thirdweb SDK so that we can use it in our other scripts
export default sdk;

**Comment by nachoiacovino** [comment]
I recommend removing your node_modules and installing again or starting from scratch from here: https://github.com/thirdweb-dev/buildspace-dao-starter

**Comment by Artedys** [comment]
Hi Naco, Thank you for these advices. 

I am in Replit not in Terminal

In Replit, 

In Replit I started with buildspace-dao-starter

I upgraded to latest node version, and again node scripts/1-initialize-sdk.js
file:///home/runner/10-Novembre-buildspace-dao-starter-v3/scripts/1-initialize-sdk.js:20
const sdk = ThirdwebSDK.fromPrivateKey(
                        ^

TypeError: ThirdwebSDK.fromPrivateKey is not a function
    at file:///home/runner/10-Novembre-buildspace-dao-starter-v3/scripts/1-initialize-sdk.js:20:25
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1

In Replit the OLD version of script 1 pass, but this function "const sdk = ThirdwebSDK.fromPrivateKey(" doesn't pass.

I guess you do tests in Terminal !

I guess in Terminal it works ?

Correct ?

**Comment by Artedys** [comment]
<img width="632" alt="Capture d’écran 2022-11-11 à 19 36 19" src="https://user-images.githubusercontent.com/8425280/201408473-2c9c25f3-ac25-415d-80ee-fee5d7c567e8.png">
Nacho: I confirm the OLD code in script 1 initialize is OK = is working.

Moreover you changed the index.jsx code and is NOK = not working at all.

Question: Who is the person in buildspace who is doing tests before releases ?

Please find here the screenshot with the new index.jsx file (final) = NOK
<img width="1039" alt="Capture d’écran 2022-11-11 à 19 40 18" src="https://user-images.githubusercontent.com/8425280/201409123-b4be036c-c862-40cf-ad5e-73c35d1b41d9.png">

PS: I am in Replit v3 / not in terminal

**Comment by Artedys** [comment]
I close because it works OK in TERMINAL / but with a issue in REPLIT

**Comment by Artedys** [comment]
I close because it works OK in TERMINAL / but with a issue in REPLIT
<img width="609" alt="Capture d’écran 2022-11-12 à 12 59 46" src="https://user-images.githubusercontent.com/8425280/201473244-68de91d0-b3a4-460a-911e-dd25fdc50566.png">
